// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6HwnRzHvYL31BiIquaczsc30260JmrAw',
    appId: '1:629317851224:web:f696c60684e2c48a1a122d',
    messagingSenderId: '629317851224',
    projectId: 'fir-practice-absoft',
    authDomain: 'fir-practice-absoft.firebaseapp.com',
    storageBucket: 'fir-practice-absoft.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOjjtkGhZPfE6F5M9SD6tKR87KIFQzE14',
    appId: '1:629317851224:android:9f30b28e006f33581a122d',
    messagingSenderId: '629317851224',
    projectId: 'fir-practice-absoft',
    storageBucket: 'fir-practice-absoft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEHa_WGqDsMAe6rs7DzfGqu7Fvv90yqdo',
    appId: '1:629317851224:ios:78653aa93bf716e51a122d',
    messagingSenderId: '629317851224',
    projectId: 'fir-practice-absoft',
    storageBucket: 'fir-practice-absoft.appspot.com',
    iosBundleId: 'com.absoftsolution.firebassePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEHa_WGqDsMAe6rs7DzfGqu7Fvv90yqdo',
    appId: '1:629317851224:ios:78653aa93bf716e51a122d',
    messagingSenderId: '629317851224',
    projectId: 'fir-practice-absoft',
    storageBucket: 'fir-practice-absoft.appspot.com',
    iosBundleId: 'com.absoftsolution.firebassePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6HwnRzHvYL31BiIquaczsc30260JmrAw',
    appId: '1:629317851224:web:9188a21b71bd1dbd1a122d',
    messagingSenderId: '629317851224',
    projectId: 'fir-practice-absoft',
    authDomain: 'fir-practice-absoft.firebaseapp.com',
    storageBucket: 'fir-practice-absoft.appspot.com',
  );
}
